Add function to load boolean values from config
INCF/MUSIC pull request #49
Opened 2017-10-24 20:38 UTC by jakobj

This PR adds a function that allows loading of boolean values from a config. Values need to be defined as `true`/`false`. See here https://github.com/incf-music/music-adapters/pull/5/files for a use case.

2017-10-25 07:57 UTC, mdjurfeldt requested changes
Thank you for this addition! Can I just bother you with fixing the indentation? There are a few spaces to add between function names and start of argument lists. It's cleaner if you fix it than if I do.

2017-10-25 12:11 UTC, jakobj commented
Sure I can fix it, but I am not sure what convention to follow exactly. To my naive eye the added code looks similar to the code surrounding it. Or do you mean in the whole file? Do you have conventions written down somewhere?

2017-10-25 14:07 UTC, mdjurfeldt commented
Sure---it's these standards:

https://www.gnu.org/prep/standards/

Yes, unfortunately unformatted code has slipped in, but I am going to work
towards a cleanup and am trying to enforce the coding style.

What I saw in your code was just a few missing spaces between function name
and left paren.

Den 25 okt. 2017 14:11 skrev "Jakob Jordan" <notifications@github.com>:

> Sure I can fix it, but I am not sure what convention to follow exactly. To
> my naive eye the added code looks similar to the code surrounding it. Or do
> you mean in the whole file? Do you have conventions written down somewhere?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/INCF/MUSIC/pull/49#issuecomment-339309274>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ADcfCUSUouVrXwsAoWFdoGkB25meqQJbks5svyVdgaJpZM4QFDj->
> .
>

2017-10-26 09:52 UTC, jakobj commented
Thanks for the link. I've now added the few missing whitespaces.

2017-10-26 10:17 UTC, merged